# Generated by Django 5.1.6 on 2025-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('user_ip', models.GenericIPAddressField()),
                ('user_name', models.TextField()),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('text_name', models.TextField()),
            ],
        ),
    ]
