# Generated by Django 5.1.6 on 2025-03-05 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_and_show', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_text',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_texts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_text',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_and_show.user_text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
