# Generated by Django 5.1.6 on 2025-03-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_and_show', '0003_essay_essayrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayrating',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='essayrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_text',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Essay',
        ),
        migrations.DeleteModel(
            name='EssayRating',
        ),
    ]
