# Generated by Django 5.1.6 on 2025-03-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_and_show', '0005_alter_userrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
