# Generated by Django 5.1.6 on 2025-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_and_show', '0006_alter_userrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_text',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
